### ISSUE TITLE
Your program not working

### ISSUE THREAD

**Issue by Aptura** [AeX03/Figged-Wallet-BTC#2]
You can't just tell to people that working because is just impossible.

**Comment by AeX03** [comment]
it's true it's more profitable to work, the site that allowed the program to work and down so the program and down

**Comment by Aptura** [comment]
No it's just impossible to "decrypt btc wallets" that's it.

**Comment by Aptura** [comment]
And Windows Defender flag your release be like a Trojan and the source code zip contain no code !

**Comment by AeX03** [comment]
for everything for my part the project launches correctly and my pc does not tell me that there is a virus while I have norton here is a proof that you can watch on this link : https://github.com/AeX03/Figged-Wallet-BTC#preview-2022
@Aptura

**Comment by AeX03** [comment]
I'm not saying that I don't believe you but for my part it works... maybe a problem of requirements or Python3.6 did you check the little box before installing pyton3.6 all at the bottom ?
